# Generated by Django 3.0.5 on 2021-01-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('profile_picture', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300, unique=True)),
                ('phone_number', models.CharField(max_length=300)),
                ('room_number', models.CharField(max_length=300)),
                ('subject', models.ManyToManyField(to='teachers.Subject')),
            ],
        ),
    ]
